version: "3.4"

x-logging:
  &default-logging
  driver: json-file
  options:
    max-size: "1g"

services:
  app:
    ports:
      - "80:80"
    image: iot-roomme:1.0.0
    logging: *default-logging
  db:
    image: mongo:bionic
    logging: *default-logging
    volumes:
      - ./db:/data/db
